/**
 * Helper functions for building BPMN element mappings and parent paths
 */

import { supabase } from '@/integrations/supabase/client';

export interface DependencyInfo {
  parentFile: string;
  callActivityName: string;
}

/**
 * Builds a parent path recursively from dependencies
 * Robust against missing subprocess files and potential cycles in bpmn_dependencies
 */
export async function buildParentPath(
  fileName: string,
  depsMap: Map<string, DependencyInfo>,
  visited: Set<string> = new Set()
): Promise<string[]> {
  if (visited.has(fileName)) {
    // Cycle detected in bpmn_dependencies when building parentPath
    return [];
  }
  visited.add(fileName);

  const dep = depsMap.get(fileName);
  if (!dep) return []; // Top-level file without registered parent

  const parentRoot = dep.parentFile
    .replace('.bpmn', '')
    .replace(/^mortgage-se-/, '')
    .replace(/-/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());

  const capitalizedRoot =
    parentRoot.charAt(0).toUpperCase() + parentRoot.slice(1);

  const grandparentPath = await buildParentPath(dep.parentFile, depsMap, visited);

  return [...grandparentPath, capitalizedRoot];
}

/**
 * Loads all dependencies from the database and creates a map
 */
export async function loadDependenciesMap(): Promise<Map<string, DependencyInfo>> {
  const { data: allDependencies } = await supabase
    .from('bpmn_dependencies')
    .select('parent_file, child_process, child_file');
  
  const depsMap = new Map<string, DependencyInfo>();
  if (allDependencies) {
    for (const dep of allDependencies) {
      if (dep.child_file) {
        depsMap.set(dep.child_file, {
          parentFile: dep.parent_file,
          callActivityName: dep.child_process,
        });
      }
    }
  }
  return depsMap;
}

/**
 * Builds BPMN element mappings for a single file
 * Returns mappings to insert and detailed Jira mappings
 */
export async function buildMappingsForFile(
  bpmnFileName: string,
  depsMap: Map<string, DependencyInfo>
): Promise<{
  mappingsToInsert: any[];
  detailedJiraMappings: Array<{ elementId: string; elementName: string; jiraType: string; jiraName: string }>;
}> {
  const mappingsToInsert: any[] = [];
  const detailedJiraMappings: Array<{ elementId: string; elementName: string; jiraType: string; jiraName: string }> = [];

  try {
    const bpmnUrl = `/bpmn/${bpmnFileName}`;
    const { buildBpmnHierarchy } = await import('@/lib/bpmnHierarchy');
    
    // Build parentPath from dependencies
    const parentPath = await buildParentPath(bpmnFileName, depsMap);
    const hierarchy = await buildBpmnHierarchy(bpmnFileName, bpmnUrl, parentPath);
    
    // Extract all nodes from hierarchy (hierarchy.allNodes is already a flat list)
    const allNodes = hierarchy.allNodes;
    
    // Create mappings for each node (only jira_type, not jira_name)
    for (const node of allNodes) {
      mappingsToInsert.push({
        bpmn_file: node.bpmnFile,
        element_id: node.id,
        jira_type: node.jiraType || null,
        // jira_name: NOT set here - generated by handleBuildHierarchy instead
      });
      
      if (node.jiraType) {
        detailedJiraMappings.push({
          elementId: node.id,
          elementName: node.name,
          jiraType: node.jiraType,
          jiraName: '', // Empty - comes from handleBuildHierarchy
        });
      }
    }
  } catch (error) {
    console.error(`Error building mappings for ${bpmnFileName}:`, error);
  }

  return { mappingsToInsert, detailedJiraMappings };
}

/**
 * Saves element mappings to the database
 */
export async function saveElementMappings(mappingsToInsert: any[]): Promise<void> {
  if (mappingsToInsert.length === 0) return;

  const { error: mappingsError } = await supabase
    .from('bpmn_element_mappings')
    .upsert(mappingsToInsert, {
      onConflict: 'bpmn_file,element_id',
      ignoreDuplicates: false,
    });

  if (mappingsError) {
    // Check if it's a foreign key constraint error (user_id doesn't exist)
    // This can happen after database reset when user session is invalid
    const isForeignKeyError = mappingsError.code === '23503' || 
      mappingsError.message?.includes('foreign key constraint') ||
      mappingsError.message?.includes('user_id');
    
    if (isForeignKeyError) {
      // Save element mappings error (user session invalid - mappings saved but version creation skipped)
      // Mappings are still saved, but version creation failed - this is ok
    } else {
      console.error('Save element mappings error:', mappingsError);
    }
  }
}

