-- Update reset_generated_data function to clear all autogenerated data
CREATE OR REPLACE FUNCTION public.reset_generated_data()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  dor_dod_count int;
  test_links_count int;
  docs_count int;
  result jsonb;
BEGIN
  -- Check if user is authenticated
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Unauthorized: User must be authenticated';
  END IF;

  -- Count rows before deletion
  SELECT COUNT(*) INTO dor_dod_count FROM dor_dod_status;
  SELECT COUNT(*) INTO test_links_count FROM node_test_links;
  
  -- Check if bpmn_docs table exists and count
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'bpmn_docs') THEN
    EXECUTE 'SELECT COUNT(*) FROM bpmn_docs' INTO docs_count;
  ELSE
    docs_count := 0;
  END IF;

  -- Truncate autogenerated tables
  TRUNCATE TABLE dor_dod_status RESTART IDENTITY;
  TRUNCATE TABLE node_test_links RESTART IDENTITY;
  
  -- Truncate bpmn_docs if it exists
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'bpmn_docs') THEN
    EXECUTE 'TRUNCATE TABLE bpmn_docs RESTART IDENTITY';
  END IF;

  -- Build result
  result := jsonb_build_object(
    'success', true,
    'deleted', jsonb_build_object(
      'dor_dod_status', dor_dod_count,
      'node_test_links', test_links_count,
      'bpmn_docs', docs_count
    ),
    'preserved', jsonb_build_object(
      'bpmn_files', (SELECT COUNT(*) FROM bpmn_files),
      'node_references', (SELECT COUNT(*) FROM node_references),
      'test_results', (SELECT COUNT(*) FROM test_results)
    )
  );

  RETURN result;
END;
$function$;