-- Create node_references table for manual links (Figma, Jira, etc.)
CREATE TABLE IF NOT EXISTS public.node_references (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  bpmn_file text NOT NULL,
  bpmn_element_id text NULL,
  ref_type text NOT NULL CHECK (ref_type IN ('figma', 'jira', 'confluence', 'other')),
  ref_label text NOT NULL,
  ref_url text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Add indexes for efficient queries
CREATE INDEX idx_node_references_bpmn_file ON public.node_references(bpmn_file);
CREATE INDEX idx_node_references_element_id ON public.node_references(bpmn_element_id);
CREATE INDEX idx_node_references_type ON public.node_references(ref_type);

-- Enable RLS
ALTER TABLE public.node_references ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Anyone can view node references"
  ON public.node_references FOR SELECT
  USING (true);

CREATE POLICY "Authenticated users can insert node references"
  ON public.node_references FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can update node references"
  ON public.node_references FOR UPDATE
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can delete node references"
  ON public.node_references FOR DELETE
  USING (auth.uid() IS NOT NULL);

-- Trigger for updated_at
CREATE TRIGGER update_node_references_updated_at
  BEFORE UPDATE ON public.node_references
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Create admin function to reset generated data
CREATE OR REPLACE FUNCTION public.reset_generated_data()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  dor_dod_count int;
  test_links_count int;
  result jsonb;
BEGIN
  -- Check if user is authenticated
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Unauthorized: User must be authenticated';
  END IF;

  -- Count rows before deletion
  SELECT COUNT(*) INTO dor_dod_count FROM dor_dod_status;
  SELECT COUNT(*) INTO test_links_count FROM node_test_links;

  -- Truncate autogenerated tables
  TRUNCATE TABLE dor_dod_status RESTART IDENTITY;
  TRUNCATE TABLE node_test_links RESTART IDENTITY;

  -- Build result
  result := jsonb_build_object(
    'success', true,
    'deleted', jsonb_build_object(
      'dor_dod_status', dor_dod_count,
      'node_test_links', test_links_count
    ),
    'preserved', jsonb_build_object(
      'bpmn_files', (SELECT COUNT(*) FROM bpmn_files),
      'node_references', (SELECT COUNT(*) FROM node_references)
    )
  );

  RETURN result;
END;
$$;