// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Stöd både Vite (import.meta.env) och Node/skript (process.env)
const VITE_ENV =
  typeof import.meta !== 'undefined' && (import.meta as any).env
    ? ((import.meta as any).env as Record<string, any>)
    : ({} as Record<string, any>);

const NODE_ENV: Record<string, any> =
  typeof process !== 'undefined' && (process as any).env
    ? ((process as any).env as Record<string, any>)
    : {};

const SUPABASE_URL =
  VITE_ENV.VITE_SUPABASE_URL || NODE_ENV.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  VITE_ENV.VITE_SUPABASE_PUBLISHABLE_KEY ||
  NODE_ENV.VITE_SUPABASE_PUBLISHABLE_KEY;
const APP_ENV = (VITE_ENV.VITE_APP_ENV || NODE_ENV.VITE_APP_ENV || 'production') as
  | 'production'
  | 'test'
  | string;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Known test Supabase project URL (hardcoded for safety)
const KNOWN_TEST_SUPABASE_URL = 'https://jxtlfdanzclcmtsgsrdd.supabase.co';

// Provide fallback values to prevent crashes if env vars are missing,
// but enforce stricter checks when running in the dedicated test environment.
const supabaseUrl = SUPABASE_URL || '';
const supabaseKey = SUPABASE_PUBLISHABLE_KEY || '';

// SAFETY GUARDRAILS: Prevent tests from accidentally hitting production
if (APP_ENV === 'test') {
  if (!supabaseUrl) {
    throw new Error(
      '[supabase] VITE_APP_ENV=test but VITE_SUPABASE_URL is empty. ' +
        'Configure .env.test with your test Supabase URL: ' + KNOWN_TEST_SUPABASE_URL,
    );
  }

  if (!supabaseUrl.includes('jxtlfdanzclcmtsgsrdd')) {
    throw new Error(
      '[supabase] SAFETY CHECK FAILED: VITE_APP_ENV=test but VITE_SUPABASE_URL does not point to the test project!\n' +
        '  Expected: ' + KNOWN_TEST_SUPABASE_URL + '\n' +
        '  Got: ' + supabaseUrl + '\n' +
        '  Tests must use the dedicated test Supabase project, not production.\n' +
        '  Check your .env.test file.',
    );
  }

  // Log confirmation in development
  const isDev = VITE_ENV.DEV || NODE_ENV.NODE_ENV === 'development';
  if (isDev) {
    console.log('[supabase] ✅ Running in TEST mode with test Supabase project:', supabaseUrl);
  }
}

export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
  auth: {
    // I browsern: använd localStorage, i Node/skript: ingen persistent storage
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: typeof window !== 'undefined',
    autoRefreshToken: true,
  },
});

// Exponera Supabase client via window för Playwright-tester
// OBS: Detta exponeras alltid i development för att underlätta testning
if (typeof window !== 'undefined') {
  // @ts-ignore
  window.__SUPABASE_CLIENT__ = supabase;
}
